# -*- coding: utf-8 -*-
"""RED HAND FILE -- NLP_ex03_Sara Di Donna.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HVzCIo7uV0CB1UGrtx6jvIwd5GkPn3gN
"""

!pip install unbabel-comet
!pip install sacremoses
!python -m pytorch_lightning.utilities.upgrade_checkpoint ../root/.cache/huggingface/hub/models--Unbabel--wmt22-comet-da/snapshots/371e9839ca4e213dde891b066cf3080f75ec7e72/checkpoints/model.ckpt
from transformers import MarianMTModel, MarianTokenizer
import os
import sacremoses
import re
from comet import download_model, load_from_checkpoint

os.environ['HF_TOKEN'] = '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' # token needed to access transformer model from Hugging Face

# Load the MarianMT model and tokenizer for translation between English and Italian
model_name = 'Helsinki-NLP/opus-mt-en-it'  # English to Italian translation model
tokenizer = MarianTokenizer.from_pretrained(model_name)
model = MarianMTModel.from_pretrained(model_name)

# define a function for segment-level translation
def segment_level_translation(text_segments, model, tokenizer, max_length=700):
    translations = []
    for segment in text_segments:
        inputs = tokenizer.encode(segment, return_tensors="pt", max_length=max_length, truncation=True)
        outputs = model.generate(inputs, max_length=max_length, num_beams=4, early_stopping=True)
        translated_text = tokenizer.decode(outputs[0], skip_special_tokens=True)
        translations.append(translated_text)
    return translations

#Text to be translated
text = "Dear Clara, Our values can be temporary and exist in a state of flux. I would not suggest that you change your values, because they are at any given time a crucial part of our nature and critical to the development of the world. My suggestion would be to instead look to two qualities that will improve your life. The first is humility. Humility amounts to an understanding that the world is not divided into good and bad people, but rather it is made up of all manner of individuals, each broken in their own way, each caught up in the common human struggle and each having the capacity to do both terrible and beautiful things. The other quality is curiosity. If you look with curiosity at people who do not share your values, they become interesting rather than threatening. Clara, my advice, then, is to try to make more use of humility and curiosity – these attributes have a softening effect on our sometimes inflexible and isolating value systems. Love, Nick"

# Regular expression to split the text in sentences
segments = re.split(r'(?<=[^A-Z].[.?])\s+', text)

# Perform segment-level translation
translations = segment_level_translation(segments, model, tokenizer)

# Print the translations
print("Red Hand File - segment level translation:")
for i, translation in enumerate(translations):
    print(f"Segment {i+1} (Source): {segments[i]}")
    print(f"Segment {i+1} (Target): {translation}\n")

def document_level_translation(document, model, tokenizer):
    # Tokenize the entire document
    input_ids = tokenizer.encode(document, return_tensors="pt", truncation=True)

    # Generate translations for the entire document
    max_length = 2500  # Maximum length for the generated output
    outputs = model.generate(input_ids, max_length=max_length, num_beams=10, early_stopping=True)

    # Decode the translations
    translated_document = tokenizer.decode(outputs[0], skip_special_tokens=True)
    return translated_document

# Perform document-level translation
translated_document = document_level_translation(text, model, tokenizer)

# Print the translated document
print("Red Hand File - document level translation:")
print("Source:")
print(text)
print("\nTarget:")
print(translated_document)

# ##COMET: Red Hand File - SEGMENT-LEVEL

model_path = download_model("Unbabel/wmt22-comet-da")
model = load_from_checkpoint(model_path)

# Translation data, where: "src" is the English source text, "mt" is the machine translation output provided by the segment-level translation function and "ref" is the corresponding translation nugget by nugget produced by a native
doc_data = [
    {
        "src": "Dear Clara, Our values can be temporary and exist in a state of flux.",
        "mt": "Cara Clara, i nostri valori possono essere temporanei ed esistere in uno stato di flusso.",
        "ref": "Cara Clara, i nostri valori possono essere temporanei ed esistere in uno stato di flusso."
    },
    {
        "src": "I would not suggest that you change your values, because they are at any given time a crucial part of our nature and critical to the development of the world.",
        "mt": "Non vi suggerirei di cambiare i vostri valori, perché sono in qualsiasi momento una parte cruciale della nostra natura e fondamentali per lo sviluppo del mondo.",
        "ref": "Non ti suggerirei di cambiare i tuoi valori, perché in ogni momento sono una parte cruciale della nostra natura e fondamentali per lo sviluppo del mondo."
    },
      {
        "src": "My suggestion would be to instead look to two qualities that will improve your life.",
        "mt": "Il mio suggerimento sarebbe quello di guardare invece a due qualità che miglioreranno la vostra vita.",
        "ref": "Il mio suggerimento sarebbe quello di guardare invece a due qualità che miglioreranno la tua vita."
    },
      {
        "src": "The first is humility.",
        "mt": "La prima è l'umiltà.",
        "ref": "La prima è l'umiltà."
    },
      {
        "src": "Humility amounts to an understanding that the world is not divided into good and bad people, but rather it is made up of all manner of individuals, each broken in their own way, each caught up in the common human struggle and each having the capacity to do both terrible and beautiful things.",
        "mt": "L'umiltà consiste nella comprensione che il mondo non è diviso in persone buone e cattive, ma piuttosto è composto da ogni tipo di individuo, ciascuno rotto a modo loro, ognuno coinvolto nella lotta umana comune e ciascuno ha la capacità di fare cose terribili e belle.",
        "ref": "L'umiltà consiste nel comprendere che il mondo non è diviso in persone buone e cattive, ma piuttosto è composto da qualsiasi tipologia di individuo, ognuno distrutto a modo suo, ognuno coinvolto nella lotta umana comune e ognuno con la capacità di fare sia cose terribili che belle."
    },
      {
        "src": "The other quality is curiosity.",
        "mt": "L'altra qualità è la curiosità.",
        "ref": "L'altra qualità è la curiosità."
    },
      {
        "src": "If you look with curiosity at people who do not share your values, they become interesting rather than threatening.",
        "mt": "Se guardate con curiosità a persone che non condividono i vostri valori, diventano interessanti piuttosto che minacciosi.",
        "ref": "Se guardi con curiosità a persone che non condividono i tuoi valori, diventano interessanti piuttosto che minacciose."
    },
      {
        "src": "Clara, my advice, then, is to try to make more use of humility and curiosity – these attributes have a softening effect on our sometimes inflexible and isolating value systems.",
        "mt": "Clara, il mio consiglio, quindi, è quello di cercare di fare più uso di umiltà e curiosità questi attributi hanno un effetto ammorbidente sui nostri a volte inflessibili e isolanti sistemi di valore.",
        "ref": "Clara, il mio consiglio, quindi, è quello di cercare di fare più uso di umiltà e curiosità: questi attributi hanno un effetto ammorbidente sui nostri sistemi di valore a volte inflessibili e isolanti."
    },
      {
        "src": "Love, Nick",
        "mt": "Con amore, Nick",
        "ref": "Con affetto, Nick"
    }
]
doc_model_output = model.predict(doc_data, batch_size=8, gpus=1)
print (doc_model_output)

##COMET: Red Hand File - DOC-LEVEL

model_path = download_model("Unbabel/wmt22-comet-da")
model = load_from_checkpoint(model_path)

# Translation data, where "src" is the English source text, "mt" is the machine translation output provided by the document-level translation and "ref" is a human produced translation
doc_data = [
    {
        "src": "Dear Clara, Our values can be temporary and exist in a state of flux. I would not suggest that you change your values, because they are at any given time a crucial part of our nature and critical to the development of the world. My suggestion would be to instead look to two qualities that will improve your life. The first is humility. Humility amounts to an understanding that the world is not divided into good and bad people, but rather it is made up of all manner of individuals, each broken in their own way, each caught up in the common human struggle and each having the capacity to do both terrible and beautiful things. The other quality is curiosity. If you look with curiosity at people who do not share your values, they become interesting rather than threatening. Clara, my advice, then, is to try to make more use of humility and curiosity – these attributes have a softening effect on our sometimes inflexible and isolating value systems. Love, Nick",
        "mt": "Cara Clara, i nostri valori possono essere temporanei ed esistere in uno stato di flusso. Non suggerirei di cambiare i tuoi valori, perché sono in qualsiasi momento una parte cruciale della nostra natura e critica per lo sviluppo del mondo. Il mio suggerimento sarebbe quello di guardare invece a due qualità che miglioreranno la vostra vita. Il primo è l'umiltà. L'umiltà equivale ad una comprensione che il mondo non è diviso in persone buone e cattive, ma piuttosto è fatta di ogni tipo di individui, ciascuno rotto a modo loro, ognuno coinvolto nella lotta umana comune e ciascuno avere la capacità di fare sia cose terribili e belle. L'altra qualità è la curiosità. Se si guarda con curiosità a persone che non condividono i vostri valori, diventano interessanti piuttosto che minacciosi. Clara, il mio consiglio, allora, è quello di cercare di fare più uso di umiltà e curiosità questi attributi hanno un effetto attenuante sui nostri a volte inflessibili ed isolanti sistemi di valore.",
        "ref": "Cara Clara, i nostri valori possono essere temporanei ed esistere in uno stato di flusso. Non ti suggerirei di cambiare i tuoi valori, perché in ogni momento sono una parte cruciale della nostra natura e fondamentali per lo sviluppo del mondo. Il mio suggerimento sarebbe quello di guardare invece a due qualità che miglioreranno la tua vita. La prima è l'umiltà. L'umiltà consiste nel comprendere che il mondo non è diviso in persone buone e cattive, ma piuttosto è composto da qualsiasi tipologia di individuo, ognuno distrutto a modo suo, ognuno coinvolto nella lotta umana comune e ognuno con la capacità di fare sia cose terribili che belle. L'altra qualità è la curiosità. Se guardi con curiosità a persone che non condividono i tuoi valori, diventano interessanti piuttosto che minacciose. Clara, il mio consiglio, quindi, è quello di cercare di fare più uso di umiltà e curiosità: questi attributi hanno un effetto ammorbidente sui nostri sistemi di valore a volte inflessibili e isolanti. Con affetto, Nick."
    }
]
doc_model_output = model.predict(doc_data, batch_size=8, gpus=1)
print (doc_model_output)